### ISSUE TITLE
Tests failed on 44e6fe938f4052e5a71e6595dac10c6ef51b665e

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit-machines#1742] opened 2024-07-27 02:26 UTC
The job `fedora-40/updates-testing` failed on commit 44e6fe938f4052e5a71e6595dac10c6ef51b665e.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-44e6fe93-20240727-015940-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment] 2024-07-28 06:24
Duplicate of #1739

**Closed by martinpitt** 2024-07-28 06:24 UTC
Labels: nightly

**Comment by martinpitt** [comment] 2024-07-28 06:31
This is a duplicate of #1743 instead. Same tests failed, but for a different reason.
