### ISSUE TITLE
Windows Virtual Machines displaying incorrect Memory Usage

### ISSUE THREAD

**Issue by aaronprisk** [cockpit-project/cockpit-machines#253] opened 2021-07-14 15:23 UTC
We've noticed that our Windows guests (Windows 10, Server 2016, Server 2019) all show 100% memory usage within the Cockpit interface regardless of how much the guest is actually using. We have the latest stable virtio-guest tools installed and I can see the balloon driver service is running. 

Here's a snippet from a Windows VM:

![image](https://user-images.githubusercontent.com/16280777/125646813-d48b65c6-82e3-4328-b85f-92a864f02d29.png)

This doesn't seem to affect our Linux or FreeBSD virtual machines:

![image](https://user-images.githubusercontent.com/16280777/125646780-c3c6caa3-1e85-4927-a7f3-06a5ae5f91e6.png)

--------------------------
HOST OS: RHEL 8.4
COCKPIT VERSION: 238.2

**Comment by martinpitt** [comment] 2021-07-14 19:53
Can you please compare this with `virsh domstats` output in a terminal window? It's very likely that it's wrong there as well, i. e. somewhere between libvirt and QEMU. If the numbers are correct threre, it may also be a bug in libvirt-dbus or cockpit-machines, but as on that level the guest OS is irrelevant (and there is no guest OS conditional code), I suspect the former. Thanks!

**Comment by KKoukiou** [comment] 2021-09-23 13:29
Reporter not reposponding.

**Comment by PetrusZ** [comment] 2021-09-30 05:53
@martinpitt @KKoukiou I have same issue, but my vm OS is openwrt.

The `virsh dostats` output is:

```
Domain: 'openwrt'
  state.state=1
  state.reason=1
  cpu.time=248951641477400
  cpu.user=13534990000000
  cpu.system=143079020000000
  cpu.cache.monitor.count=0
  balloon.current=1048576
  balloon.maximum=1048576
  balloon.swap_in=0
  balloon.swap_out=0
  balloon.major_fault=0
  balloon.minor_fault=0
  balloon.unused=998328
  balloon.available=1007156
  balloon.usable=988580
  balloon.last-update=1632615018
  balloon.disk_caches=0
  balloon.rss=1191844
  vcpu.current=2
  vcpu.maximum=2
  vcpu.0.state=1
  vcpu.0.time=88588760000000
  vcpu.0.wait=0
  vcpu.0.delay=512478736615
  vcpu.1.state=1
  vcpu.1.time=127412830000000
  vcpu.1.wait=0
  vcpu.1.delay=456018037164
  net.count=1
  net.0.name=vnet0
  net.0.rx.bytes=1381487571771
  net.0.rx.pkts=2087717777
  net.0.rx.errs=0
  net.0.rx.drop=751
  net.0.tx.bytes=3058640748670
  net.0.tx.pkts=2679776797
  net.0.tx.errs=0
  net.0.tx.drop=0
  block.count=1
  block.0.name=hdb
  block.0.path=/var/lib/libvirt/images/06.12-openwrt-x86-64-generic-squashfs-combined.img
  block.0.backingIndex=1
  block.0.rd.reqs=12433
  block.0.rd.bytes=68621312
  block.0.rd.times=409072723
  block.0.wr.reqs=1415
  block.0.wr.bytes=98344960
  block.0.wr.times=270511942
  block.0.fl.reqs=156
  block.0.fl.times=154237790
  block.0.allocation=161021952
  block.0.capacity=1606942720
  block.0.physical=1606950912
  dirtyrate.calc_status=0
  dirtyrate.calc_start_time=0
  dirtyrate.calc_period=0
```

Which number is used by cockpit-machines for Memory Usage?

BTW, in openwrt the `free -m` shows:

```
root@OPENWRT:~# free -m
              total        used        free      shared  buff/cache   available
Mem:        1011408      107308      698668       13196      205432      830524
Swap:             0           0           0
```

**Comment by KKoukiou** [comment] 2021-09-30 10:05
We use RSS / CURRENT. From the domstats values above we use   balloon.rss=1191844 /  balloon.current=1048576

I see indeed that the first value is larger, so we need to take a look into that.

**Comment by KKoukiou** [comment] 2021-09-30 10:23
There is a whole thread here discussing why RSS / Total can be greater than 100% as you see, https://libvir-list.redhat.narkive.com/0xg544qp/libvirt-kvm-domain-memory-and-disk-usage 

I will make sure to spend some time on this and clarify the behavior.

**Comment by KKoukiou** [comment] 2023-12-14 11:49
Duplicate of #49

**Closed by KKoukiou** 2023-12-14 11:49 UTC
