### ISSUE TITLE
Tests failed on 5baebf863be2f6f7ede5e5ab2bef165457ecbe6f

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit-machines#1916] opened 2024-11-22 02:42 UTC
The job `fedora-40/updates-testing` failed on commit 5baebf863be2f6f7ede5e5ab2bef165457ecbe6f.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-5baebf86-20241122-022058-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment] 2024-11-22 08:11
Duplicate of #1913

**Closed by martinpitt** 2024-11-22 08:11 UTC
Labels: nightly
