### ISSUE TITLE
Tests failed on 244642134a963e5c59c93ca43714eb6442cc26d6

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit-machines#1748] opened 2024-07-31 02:05 UTC
The job `fedora-40/updates-testing` failed on commit 244642134a963e5c59c93ca43714eb6442cc26d6.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-24464213-20240731-013909-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment] 2024-07-31 05:06
Duplicate of #1743

**Closed by martinpitt** 2024-07-31 05:06 UTC
Labels: nightly
