### ISSUE TITLE
Bug - Popovers in Import and Create VM dialogs are broken

### ISSUE THREAD

**Issue by subhoghoshX** [cockpit-project/cockpit-machines#1100] opened 2023-06-05 07:56 UTC
![image](https://github.com/cockpit-project/cockpit-machines/assets/108616679/68e87097-0909-4e61-b11f-503ef4b13309)

![image](https://github.com/cockpit-project/cockpit-machines/assets/108616679/a2fed4f7-f738-47b4-81e1-a559146c30e3)

**Comment by garrett** [comment] 2023-06-07 15:26
This is a combination of issues:

1. The popup's parent is inside the content of the modal, so it is cropped on the scrollable viewport and causes an overflow, making it scroll.
2. The width is not correct (it should be wider)
3. The z-index is incorrect.

If I add z-index to the row's parent `#connection` / `.machines-connection-selector`, I get this, which is still not correct:

![image](https://github.com/cockpit-project/cockpit-machines/assets/10246/99d36b24-42e9-4603-8f38-348179e04f02)

... but perhaps all of this would be fixed by setting the parent to the modal or higher?

**Comment by garrett** [comment] 2023-06-07 15:26
(Also: When did this regression happen? Was it a PF5-related change? Could it affect other parts of Cockpit / Cockpit-Machines?)

**Comment by KKoukiou** [comment] 2023-06-08 08:01
> (Also: When did this regression happen? Was it a PF5-related change? Could it affect other parts of Cockpit / Cockpit-Machines?)

I believe it happened with the move to Pf5 because popovers became by default inline. So they get placed directy next to the trigger element in the DOM, instead of the document.body which was previously the case. They made this change in PF for accessibility purposes.

**Comment by KKoukiou** [comment] 2023-06-08 08:16
This does not seem to be a patternfly bug. I was not able to reproduce outside of cockpit.
https://codesandbox.io/s/tkw08w

**Comment by subhoghoshX** [comment] 2023-06-08 09:28
> This does not seem to be a patternfly bug. I was not able to reproduce outside of cockpit. https://codesandbox.io/s/tkw08w

Is it the correct link?

**Comment by jelly** [comment] 2023-08-21 16:04
Fixed by updating to PF5 
![image](https://github.com/cockpit-project/cockpit-machines/assets/67428/e86ea137-0ae7-4bab-8f3c-d9728d9921b5)

**Closed by jelly** 2023-08-21 16:04 UTC
Labels: bug
