### ISSUE TITLE
NFS and VM Permissions

### ISSUE THREAD

**Issue by chbelle** [cockpit-project/cockpit-machines#39] opened 2021-03-27 07:21 UTC
Cockpit version: 224.2. 
OS: Cent0S 8
Page: Virtual Machines, VM, Add Disk

This maybe an issue to do with NFS. When I create a new disk on block-based storage the file permissions are correctly set - and the VM starts-up.

When I create a disk on NFS mount the permission doesn't allow the VM to start.

The error in cockpit reads:

internal error: process exited while connecting to monitor: 2021-03-27T07:18:00.959587Z qemu-kvm: -blockdev {"driver":"file","filename":"/containers/test.qcow2","node-name":"libvirt-1-storage","auto-read-only":true,"discard":"unmap"}: Could not open '/nfsexport/test.qcow2': Permission denied

The output of the ls command reads as:

-rw-------. 1 1024 users 193K Mar 27  2021 test.qcow2
-rwxrwxrwx. 1 1024 users 3.5G Mar 27  2021 os.qcow2

The odd thing when I do this on a block based storage - the permission on the test.qcow2 disk is also -rw....

**Comment by KKoukiou** [comment] 2021-04-06 11:26
Hey @chbelle, indeed, it's seems an NFS specific issue and very specific to your system. I just tried to reproduce locally, and I can actually run Vms with disks on NFS as expected. I have some more questions to be able to help you debugging, but at this point I will convert this issue to a discussion since it's specific to your system, and I will gladly follow there.

So how do you run the VM?
* Can you send me a screenshot of the create VM dialog options before you close it? I am interested on how you actually choose the destination storage of your disk. Is your default pool your NFS mountpoint?
* How do you export the directory on the server? `cat /etc/exports`
*

**Closed** 2021-04-06 11:27 UTC
