### ISSUE TITLE
Use GiB by default when showing VM memory

### ISSUE THREAD

**Issue by shodanshok** [cockpit-project/cockpit-machines#878] opened 2022-12-03 11:16 UTC
VM Overview shows, and counts, VM memory in GB rather then in GiB. On the other side, the "edit" button specifies memory in MiB/GiB. 

Example:
![Cattura](https://user-images.githubusercontent.com/13137622/205438254-07501345-2fc3-4abb-a353-0e4d135d4415.JPG)

This results in "strange" (ie: non-integer) guest memory size. The proper solution is to show installed memory in power^2 size.

**Comment by KKoukiou** [comment] 2022-12-03 11:29
Duplicate of https://github.com/cockpit-project/cockpit-machines/issues/869
Fixed in release 279. (This was released 2 days ago)

**Closed by KKoukiou** 2022-12-03 11:29 UTC

**Comment by shodanshok** [comment] 2022-12-03 11:57
I missed it, thanks for the quick fix.
