### ISSUE TITLE
Safari Memory Usage

### ISSUE THREAD

**Issue by tgwaste** [cockpit-project/cockpit-machines#395] opened 2021-09-24 16:34 UTC
On the new Safari 15 going to: Overview -> View details and history causes huge memory usage that can literally freeze the Mac. (and my Mac is not a slouch :))

I'm sure this is Apples fault but if its something you could look at.

**Comment by marusak** [comment] 2021-09-25 14:40
Duplicate of https://github.com/cockpit-project/cockpit/issues/16242

It will be released this Wednesday in version 254

**Closed by marusak** 2021-09-25 14:40 UTC
