### ISSUE TITLE
Machines: No ability to add consoles to existing VMs

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit-machines#59] opened 2020-10-13 11:19 UTC
Page: Machines

During the latest round of usability testing, we found that 8 out of 11 users had issues figuring out what caused performance issues on a VM. One of the things almost all of them tried was connecting to the VM via the console, but it did not work. This is most likely because there was no session to connect to for those VMs. @KKoukiou suggested we should add that ability, and @marusak added that _"maybe as we do in docker/podman. If there is TTY, connect to it, otherwise create a new session and connect to it"_

**Comment by KKoukiou** [comment] 2023-12-14 11:32
Duplicate of #553

**Closed by KKoukiou** 2023-12-14 11:32 UTC
Labels: enhancement
