### ISSUE TITLE
Virtual Machine page is stuck "Loading resources"

### ISSUE THREAD

**Issue by carrowood** [cockpit-project/cockpit-machines#1307] opened 2023-11-13 23:45 UTC
When I select "Virtual Machines" from the menu it just spins with "Loading Resources". I am probably doing something dumb or maybe have some older misconfigured VMs, lol. Some details:
cockpit-304-1.fc39
cockpit-machines-301.1-1.fc39

I notice the 404's have a link syntax like:
https://192.168.1.50:9090/cockpit/@localhost/*/po.manifest.js

Do I have something configured wrong? I am not viewing this from the server itself but from my desktop on my LAN using Chrome  Version 118.0.5993.120 (Official Build) (64-bit).

### Qemu XML's:
[qemu.tar.gz](https://github.com/cockpit-project/cockpit-machines/files/13342511/qemu.tar.gz)

### Console Log:

machines:13 
        
        
       GET https://192.168.1.50:9090/cockpit/@localhost/*/po.manifest.js net::ERR_ABORTED 404 (ERROR)
machines:14 
        
        
       GET https://192.168.1.50:9090/cockpit/@localhost/*/po.js net::ERR_ABORTED 404 (ERROR)
machines:1 Refused to execute script from 'https://192.168.1.50:9090/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
machines:1 Refused to execute script from 'https://192.168.1.50:9090/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
VM803:57 Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-mjCXvCiI7QM+qc3wUjLfE81NQ63GSsJcdb/iy9A0DgM='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

injectGlobalStyles @ VM803:57
injectStyleTag @ VM803:7531
extractTimeoutRules @ VM803:7506
applyRules @ VM803:7657
(anonymous) @ VM803:7630
index.js:582 Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
(anonymous) @ index.js:582
(anonymous) @ index.js:689
index.js:390 Uncaught TypeError: Cannot read properties of undefined (reading 'getAttribute')
    at G8r (index.js:390:13911)
    at Zee (index.js:390:9635)
    at Function.<anonymous> (index.js:521:5968)
    at s (index.js:30:5693)
    at index.js:30:5888
    at a (index.js:30:4740)

**Comment by rickatnight11** [comment] 2023-12-19 20:08
I'm having a similar issue, seemingly due to bugging out parsing my VM's XML file.  Error in browser console:

```
Scrollbar test exception: TypeError: document.body is null index.js:578:74889
    <anonymous> https://<redacted>:9090/cockpit/@localhost/machines/index.js:578
    <anonymous> https://<redacted>:9090/cockpit/@localhost/machines/index.js:685

XML Parsing Error: syntax error
Location: https://<redacted>:9090/cockpit/@localhost/machines/index.html#/
Line Number 1, Column 1: index.html:1:1

Uncaught TypeError: e.getElementsByTagName(...)[0] is undefined
    DHe https://<redacted>:9090/cockpit/@localhost/machines/index.js:386
    XVr https://<redacted>:9090/cockpit/@localhost/machines/index.js:520
    s https://<redacted>:9090/cockpit/@localhost/machines/index.js:30
    c https://<redacted>:9090/cockpit/@localhost/machines/index.js:30
    a https://<redacted>:9090/cockpit/@localhost/machines/index.js:30
    setTimeout handler*i https://<redacted>:9090/cockpit/@localhost/machines/index.js:30
    c https://<redacted>:9090/cockpit/@localhost/machines/index.js:30
    f https://<redacted>:9090/cockpit/@localhost/machines/index.js:30
    resolve https://<redacted>:9090/cockpit/@localhost/machines/index.js:30
    he https://<redacted>:9090/cockpit/@localhost/machines/index.js:31
    tJ https://<redacted>:9090/cockpit/@localhost/machines/index.js:26
    value https://<redacted>:9090/cockpit/@localhost/machines/index.js:26
    m https://<redacted>:9090/cockpit/@localhost/machines/index.js:30
    _ https://<redacted>:9090/cockpit/@localhost/machines/index.js:29
    dispatch_data https://<redacted>:9090/cockpit/@localhost/machines/index.js:29
    WNr https://<redacted>:9090/cockpit/@localhost/machines/index.js:26
    WNr https://<redacted>:9090/cockpit/@localhost/machines/index.js:26
    qNr https://<redacted>:9090/cockpit/@localhost/machines/index.js:27
    LB https://<redacted>:9090/cockpit/@localhost/machines/index.js:30
    jNr https://<redacted>:9090/cockpit/@localhost/machines/index.js:30
    channel https://<redacted>:9090/cockpit/@localhost/machines/index.js:30
    F https://<redacted>:9090/cockpit/@localhost/machines/index.js:31
    dbus https://<redacted>:9090/cockpit/@localhost/machines/index.js:31
    Sqr https://<redacted>:9090/cockpit/@localhost/machines/index.js:34
    <anonymous> https://<redacted>:9090/cockpit/@localhost/machines/index.js:34
    <anonymous> https://<redacted>:9090/cockpit/@localhost/machines/index.js:685
index.js:386:19201
    DHe https://<redacted>:9090/cockpit/@localhost/machines/index.js:386
    XVr https://<redacted>:9090/cockpit/@localhost/machines/index.js:520
    s https://<redacted>:9090/cockpit/@localhost/machines/index.js:30
    c https://<redacted>:9090/cockpit/@localhost/machines/index.js:30
    a https://<redacted>:9090/cockpit/@localhost/machines/index.js:30
    (Async: setTimeout handler)
    i https://<redacted>:9090/cockpit/@localhost/machines/index.js:30
    c https://<redacted>:9090/cockpit/@localhost/machines/index.js:30
    f https://<redacted>:9090/cockpit/@localhost/machines/index.js:30
    resolve https://<redacted>:9090/cockpit/@localhost/machines/index.js:30
    he https://<redacted>:9090/cockpit/@localhost/machines/index.js:31
    tJ https://<redacted>:9090/cockpit/@localhost/machines/index.js:26
    value https://<redacted>:9090/cockpit/@localhost/machines/index.js:26
    m https://<redacted>:9090/cockpit/@localhost/machines/index.js:30
    _ https://<redacted>:9090/cockpit/@localhost/machines/index.js:29
    dispatch_data https://<redacted>:9090/cockpit/@localhost/machines/index.js:29
    WNr https://<redacted>:9090/cockpit/@localhost/machines/index.js:26
    (Async: EventListener.handleEvent)
    WNr https://<redacted>:9090/cockpit/@localhost/machines/index.js:26
    qNr https://<redacted>:9090/cockpit/@localhost/machines/index.js:27
    LB https://<redacted>:9090/cockpit/@localhost/machines/index.js:30
    jNr https://<redacted>:9090/cockpit/@localhost/machines/index.js:30
    channel https://<redacted>:9090/cockpit/@localhost/machines/index.js:30
    F https://<redacted>:9090/cockpit/@localhost/machines/index.js:31
    dbus https://<redacted>:9090/cockpit/@localhost/machines/index.js:31
    Sqr https://<redacted>:9090/cockpit/@localhost/machines/index.js:34
    <anonymous> https://<redacted>:9090/cockpit/@localhost/machines/index.js:34
    <anonymous> https://<redacted>:9090/cockpit/@localhost/machines/index.js:685
```

Attached VM XML: [qemu_vm.xml.gz](https://github.com/cockpit-project/cockpit-machines/files/13719904/qemu_vm.xml.gz)

**Comment by martinpitt** [comment] 2024-01-05 08:17
@rickatnight11 That XML looks like from RHEL (machine type and emulator path). I can import it with `virsh define` on current RHEL 9.4 (nightly) just fine, and current cockpit-machines displays it. Of course I can't actually start it as I don't have any of the referenced files like haos_ova-9.4.qcow2. So I created the file as an empty qcow and took out the `br0` and `br1` definitions, and now it starts fine, and no crash.

What is your exact cockpit-machines version? Without that I can't decode the stack trace. We have 103 instances of `getElementsByTagName.*\[0\]`, so I can't just guess either. Thanks!

**Comment by martinpitt** [comment] 2024-01-05 08:30
@carrowood you can ignore the po.* warnings. It's... complicated, but we can clean them up in about a month. The interesting bit is
> Uncaught TypeError: Cannot read properties of undefined (reading 'getAttribute')

but we have 182 instances of that call. Looking at the minified JS from version 301.1 it is crashing exactly [here](https://github.com/cockpit-project/cockpit-machines/blob/6696d5a16bdf4927b820c7f9c53c5bb6add78613/src/libvirt-xml-parse.js#L531), i.e. the `<redirdev>` element does not have any `<address>` child. This comes from your Fedora20-min-install-clean.xml which looks like this:
```xml
    <redirdev bus='usb' type='spicevmc'>
    </redirdev>
    <redirdev bus='usb' type='spicevmc'>
    </redirdev>
    <redirdev bus='usb' type='spicevmc'>
    </redirdev>
    <redirdev bus='usb' type='spicevmc'>
    </redirdev>
```

So that is actually very helpful! I'll see to reproducing this in a test and fixing it.

**Comment by martinpitt** [comment] 2024-01-05 08:43
On second look, this is nothing unusual -- even the simplest `virt-install --memory 50 --pxe --virt-type qemu --os-variant alpinelinux3.8 --disk none --wait 0 --name test1 --print-xml` creates two of these, albeit with a self-closing tag (but that shouldn't matter). But libvirt rewrites it as
```
    <redirdev bus='usb' type='spicevmc'>
      <address type='usb' bus='0' port='2'/>
    </redirdev>
```
when importing it via `virsh define` or via the API. So that must be some old bug in libvirt at the time when you created these VMs.  So with current Fedora there is no way to reproduce the crash in a test, but it's nevertheless easy enough to fix.

**Closed** 2024-01-08 10:05 UTC
