### ISSUE TITLE
sanitize/adjust guest hostname

### ISSUE THREAD

**Issue by GregJohnStewart** [cockpit-project/cockpit-machines#919] opened 2023-01-20 14:26 UTC
The hostname passed to Kickstart should be sanitized/ adjusted.

For instance, if I named my VM `Test_Vm` in the Cockpit ui, I get an error in Kickstart about having an invalid character.

The guest I was attempting was Fedora 37

Perhaps spaces should be replaced with `-` instead of `_`? or maybe replace `_` with `-` when used as a hostname?

**Comment by garrett** [comment] 2023-01-30 16:19
I agree, this should be addressed somehow. (Apparently, different OSes/distros might expect different names? https://github.com/cockpit-project/cockpit-machines/issues/41#issuecomment-915290522)

I think this is a duplicate of https://github.com/cockpit-project/cockpit-machines/issues/41 — using unattended install of Ubuntu instead of Kickstart with Fedora, but basically the same problem, where I proposed a similar solution.

At least for both Fedora (and probably CentOS and RHEL as a result) and Ubuntu (and therefore probably also Debian and other Debian derivatives), this looks like the same exact issue with the same solution.

**Closed by garrett** 2023-01-30 16:19 UTC
