### ISSUE TITLE
RFE: Add a button to download VNC based vv file

### ISSUE THREAD

**Issue by yunmingyang** [cockpit-project/cockpit-machines#349] opened 2021-09-01 11:10 UTC
Description:
If only setting vnc_listen in /etc/libvirt/qemu.conf, then only "VNC" based vv file can be used. But for now, after clicking "Launch remote viewer", "Spice" based vv file is default, and we can not change it before downloading. So I think it is better to add a button to distinguish.Also, in some OSs, which are not supported "Spice", the button to download "Spice" based vv file should be hidden

Versions:
cockpit-250-1.fc34.x86_64
cockpit-machines-250-1.fc34.noarch
libvirt-dbus-1.4.0-3.fc34.x86_64

Steps:
1. Set vnc_listen to host IP, then restart libvirtd
2. Prepare a running VM
3. Enter the VM detail page
4. Select "Console type" to "Desktop viewer", then click "Launch remote viewer", after that try to use the downloaded vv file to connect the console

**Comment by KKoukiou** [comment] 2023-12-14 15:03
Duplicate of #553

**Closed by KKoukiou** 2023-12-14 15:03 UTC
