### ISSUE TITLE
Cockpit KVM mouse controller issue

### ISSUE THREAD

**Issue by brunomgrocha** [cockpit-project/cockpit-machines#225] opened 2021-06-28 17:21 UTC
Cockpit version: 239-1~bpo10+1
OS: Debian
Page:

**Comment by KKoukiou** [comment] 2021-06-28 20:25
This has been also reported on Bugzilla, it's indeed still not fixed. https://bugzilla.redhat.com/show_bug.cgi?id=1913548

**Comment by KKoukiou** [comment] 2021-06-30 12:13
Closing a duplicate of https://github.com/cockpit-project/cockpit-machines/issues/29

**Closed by KKoukiou** 2021-06-30 12:13 UTC
