### ISSUE TITLE
TestMachinesHostDevs.testHostDevAddSingleDevice flake

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit-machines#1292] opened 2023-11-07 12:40 UTC
Flake logs: https://cockpit-logs.us-east-1.linodeobjects.com/pull-5481-20231104-052435-87e823ba-arch-cockpit-project-cockpit-machines/log.html

What seems to happen is that the `Add host device` dialog is closed while we have it open, probably due to a re-render, after adding some debug logs:

```
log: mounted
log: Add host Device
log: VmDetailsPage {"state":"shut off","inactiveXML":"Object","connectionName":"system","id":"/org/libvirt/QEMU/domain/_d242ec4d_3a46_4fb3_842d_9c9d49bf0b29","name":"subVmT
est1"} {"0":"Object"} {"refreshInterval":"10000","nodeMaxMemory":"1116320"}
log: re-render vm details
log: redraw host dev actions
log: Add host Device
log: Add host Device
log: Add host Device
log: redraw host dev actions
log: umounted
```

**Comment by martinpitt** [comment] 2023-11-09 04:57
The same [happens on rawhide](https://artifacts.dev.testing-farm.io/f3a13af7-1044-4d5b-b9ff-69a0b2f65033/). I reproduced this locally after
```
TEST_OS=fedora-rawhide make prepare-check
bots/image-customize -vr 'dnf update -y >&2' fedora-rawhide
```
(to pick up the new libvirt 9.9). I got a single failure of  testHostDevAddSingleDevice out of about 10 runs, and no local failure of testHostDevAddSessionConnection.

However, there are two different SELinux failures:
```
audit: type=1400 audit(1699505670.372:521): avc:  denied  { search } for  pid=947 comm="rpc-virtqemud" name="2277" dev="proc" ino=11328 scontext=system_u:system_r:virtqemud_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=dir permissive=1
audit: type=1400 audit(1699505682.452:529): avc:  denied  { search } for  pid=947 comm="prio-rpc-virtqe" name="2304" dev="proc" ino=11480 scontext=system_u:system_r:virtqemud_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=dir permissive=1
```

I wonder why it's `permissive=1`? Our tests don't change that, and `getenforce` says "Enforcing". Huh?

**Comment by martinpitt** [comment] 2023-11-09 07:49
It's not just a simple re-render. I tried this interactively, and it does not make the dialog get hidden:
```
--- src/components/vm/vmDetailsPage.jsx
+++ src/components/vm/vmDetailsPage.jsx
@@ -17,7 +17,7 @@
  * along with Cockpit; If not, see <http://www.gnu.org/licenses/>.
  */
 import PropTypes from 'prop-types';
-import React, { useEffect } from 'react';
+import React, { useState, useEffect } from 'react';
 import cockpit from 'cockpit';
 
 import { Breadcrumb, BreadcrumbItem } from "@patternfly/react-core/dist/esm/components/Breadcrumb";
@@ -63,6 +63,10 @@ export const VmDetailsPage = ({
         // eslint-disable-next-line react-hooks/exhaustive-deps
     }, []);
 
+    const [counter, setCounter] = useState(0);
+
+    window.setTimeout(() => { setCounter(counter + 1) }, 1000);
+
     const vmActionsPageSection = (
         <PageSection className="actions-pagesection" variant={PageSectionVariants.light} isWidthLimited>
             <div className="vm-top-panel" data-vm-transient={!vm.persistent}>
@@ -163,7 +167,7 @@ export const VmDetailsPage = ({
         {
             id: `${vmId(vm.name)}-hostdevs`,
             className: "hostdevs-card",
-            title: _("Host devices"),
+            title: `Host devices ${counter}`,
             actions: <VmHostDevActions vm={vm} />,
             body: <VmHostDevCard vm={vm} nodeDevices={nodeDevices} />,
         }
@@ -237,6 +241,8 @@ export const VmDetailsPage = ({
         );
     });
 
+    console.log("XXX VmDetailsPage render", counter);
+
     return (
         <WithDialogs>
             <Page id="vm-details"
```

Neither when I do the change "more properly" via the store:
```
--- src/components/vm/vmDetailsPage.jsx
+++ src/components/vm/vmDetailsPage.jsx
@@ -44,6 +44,9 @@ import { VmSnapshotsCard, VmSnapshotsActions } from './snapshots/vmSnapshotsCard
 import VmActions from './vmActions.jsx';
 import { VmNeedsShutdown } from '../common/needsShutdown.jsx';
 
+import { updateVm } from '../../actions/store-actions.js';
+import store from "../../store.js";
+
 import './vmDetailsPage.scss';
 
 const _ = cockpit.gettext;
@@ -56,6 +59,7 @@ export const VmDetailsPage = ({
     useEffect(() => {
         // Anything in here is fired on component mount.
         onUsageStartPolling();
+        window.setTimeout(() => { store.dispatch(updateVm({ tick: Date.now() }))}, 1000);
         return () => {
             // Anything in here is fired on component unmount.
             onUsageStopPolling();
```

@jelly how sure are you that this happens because of a re-rendering?

**Comment by martinpitt** [comment] 2023-11-09 08:09
Progress! This fails fairly reliably with this sit(), and waiting a few seconds before continuing:


```diff
--- src/components/vm/hostdevs/hostDevAdd.jsx
+++ src/components/vm/hostdevs/hostDevAdd.jsx
@@ -225,12 +225,12 @@ const AddHostDev = ({ idPrefix, vm }) => {
                     isLoading={addHostDevInProgress}
                     isDisabled={addHostDevInProgress}
                     variant="primary"
-                    onClick={attach}>
+                    onClick={() => { console.log("XXX closing HostDevAdd dialog via Attaach button"); attach() }}>
                 {_("Add")}
             </Button>
             <Button id={`${idPrefix}-cancel`}
                     variant="link"
-                    onClick={Dialogs.close}>
+                    onClick={() => { console.log("XXX closing HostDevAdd dialog via cancel button"); Dialogs.close() }}>
                 {_("Cancel")}
             </Button>
         </>
@@ -240,7 +240,7 @@ const AddHostDev = ({ idPrefix, vm }) => {
         <Modal position="top"
                variant="medium"
                id={`${idPrefix}-dialog`}
-               onClose={Dialogs.close}
+               onClick={() => { console.log("XXX closing HostDevAdd dialog via X button"); Dialogs.close() }}
                title={_("Add host device")}
                footer={footer}
                isOpen>
diff --git test/check-machines-hostdevs test/check-machines-hostdevs
index 41313beb..6bd272e9 100755
--- test/check-machines-hostdevs
+++ test/check-machines-hostdevs
@@ -23,7 +23,7 @@ import xml.etree.ElementTree as ET
 
 from machineslib import VirtualMachinesCase
 from machinesxmls import PCI_HOSTDEV, SCSI_HOST_HOSTDEV, USB_HOSTDEV, USB_HOSTDEV_NONEXISTENT
-from testlib import nondestructive, test_main, wait
+from testlib import sit, nondestructive, test_main, wait
 
 virt_xml_mock = """#!/usr/bin/python
 
@@ -155,6 +155,7 @@ class TestMachinesHostDevs(VirtualMachinesCase):
                 b.wait_not_present(f"#vm-subVmTest1-hostdev-{self.vm_dev_id}-product")
                 b.click("button#vm-subVmTest1-hostdevs-add")
                 b.wait_in_text(".pf-v5-c-modal-box .pf-v5-c-modal-box__header .pf-v5-c-modal-box__title", "Add host device")
+                sit()
                 if connectionName != "session":
                     b.assert_pixels(".pf-v5-c-modal-box", "vm-hostdevs-add-dialog", skip_layouts=["rtl"])
```

and then it shows at the second sit: 

```

-> wait: ph_is_present("input#usb_device:not([disabled]):not([aria-disabled=true])")
<- {'type': 'undefined'}
-> wait: ph_is_visible("input#usb_device:not([disabled]):not([aria-disabled=true])")
<- {'type': 'undefined'}
-> ph_mouse("input#usb_device:not([disabled]):not([aria-disabled=true])","click",0,0,0,false,false,false,false)
> log: XXX closing HostDevAdd dialog via X button
<- {'type': 'undefined'}
-> wait: ph_is_present(".pf-v5-c-table input[name='checkrow0']:not([disabled]):not([aria-disabled=true])")
<- {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true
```

Yes, that's a slightly different failure point, but same root cause. This even works with `TEST_SHOW_BROWSER=1 TEST_BROWSER=firefox`. I see a giant focus ring around the X button, but *only* during the test run. With a normal interactive session, the X button is neither focused, nor does it even work -- clicking on it does nothing.

**Comment by martinpitt** [comment] 2023-11-09 08:17
Progress! This fails fairly reliably with this sit(), and waiting a few seconds before continuing:


```diff
--- src/components/vm/hostdevs/hostDevAdd.jsx
+++ src/components/vm/hostdevs/hostDevAdd.jsx
@@ -225,12 +225,12 @@ const AddHostDev = ({ idPrefix, vm }) => {
                     isLoading={addHostDevInProgress}
                     isDisabled={addHostDevInProgress}
                     variant="primary"
-                    onClick={attach}>
+                    onClick={() => { console.log("XXX closing HostDevAdd dialog via Attach button"); attach() }}>
                 {_("Add")}
             </Button>
             <Button id={`${idPrefix}-cancel`}
                     variant="link"
-                    onClick={Dialogs.close}>
+                    onClick={() => { console.log("XXX closing HostDevAdd dialog via cancel button"); Dialogs.close() }}>
                 {_("Cancel")}
             </Button>
         </>
@@ -240,7 +240,7 @@ const AddHostDev = ({ idPrefix, vm }) => {
         <Modal position="top"
                variant="medium"
                id={`${idPrefix}-dialog`}
-               onClose={Dialogs.close}
+               onClose={() => { console.log("XXX closing HostDevAdd dialog via X button"); Dialogs.close() }}
                title={_("Add host device")}
                footer={footer}
                isOpen>
diff --git test/check-machines-hostdevs test/check-machines-hostdevs
index 41313beb..6bd272e9 100755
--- test/check-machines-hostdevs
+++ test/check-machines-hostdevs
@@ -23,7 +23,7 @@ import xml.etree.ElementTree as ET
 
 from machineslib import VirtualMachinesCase
 from machinesxmls import PCI_HOSTDEV, SCSI_HOST_HOSTDEV, USB_HOSTDEV, USB_HOSTDEV_NONEXISTENT
-from testlib import nondestructive, test_main, wait
+from testlib import sit, nondestructive, test_main, wait
 
 virt_xml_mock = """#!/usr/bin/python
 
@@ -155,6 +155,7 @@ class TestMachinesHostDevs(VirtualMachinesCase):
                 b.wait_not_present(f"#vm-subVmTest1-hostdev-{self.vm_dev_id}-product")
                 b.click("button#vm-subVmTest1-hostdevs-add")
                 b.wait_in_text(".pf-v5-c-modal-box .pf-v5-c-modal-box__header .pf-v5-c-modal-box__title", "Add host device")
+                sit()
                 if connectionName != "session":
                     b.assert_pixels(".pf-v5-c-modal-box", "vm-hostdevs-add-dialog", skip_layouts=["rtl"])
```

and then it shows at the second sit: 

```

-> wait: ph_is_present("input#usb_device:not([disabled]):not([aria-disabled=true])")
<- {'type': 'undefined'}
-> wait: ph_is_visible("input#usb_device:not([disabled]):not([aria-disabled=true])")
<- {'type': 'undefined'}
-> ph_mouse("input#usb_device:not([disabled]):not([aria-disabled=true])","click",0,0,0,false,false,false,false)
> log: XXX closing HostDevAdd dialog via X button
<- {'type': 'undefined'}
-> wait: ph_is_present(".pf-v5-c-table input[name='checkrow0']:not([disabled]):not([aria-disabled=true])")
<- {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true
```

Yes, that's a slightly different failure point, but same root cause. This even works with `TEST_SHOW_BROWSER=1 TEST_BROWSER=firefox`. I see a giant focus ring around the X button, but *only* during the test run:

![out](https://github.com/cockpit-project/cockpit-machines/assets/200109/6906203c-0588-450d-b265-ba64e3321846)

With a normal interactive session, the X button is neither focused, nor does it even work -- clicking on it does nothing.

**Comment by martinpitt** [comment] 2023-11-09 09:41
I added some debug logging directly to WithDialogs:

```diff
--- ../cockpit/main/pkg/lib/dialogs.jsx	2023-10-17 14:18:19.946822723 +0200
+++ pkg/lib/dialogs.jsx	2023-11-09 10:27:46.748451925 +0100
@@ -105,9 +105,11 @@
 export const WithDialogs = ({ children }) => {
     const [dialog, setDialog] = useState(null);
 
+    console.log("XXX WithDialogs render", JSON.stringify(dialog));
+
     const Dialogs = {
-        show: setDialog,
-        close: () => setDialog(null),
+        show: v => { console.log("XXX WithDialogs.show", v); setDialog(v) },
+        close: () => { console.log("XXX WithDialogs.close"); setDialog(null) },
         isActive: () => dialog !== null
     };
```

This should tell us whether the component survived (`dialogs` moving to false, or re-initializing as `null`). And indeed:
```
-> ph_mouse("button#vm-subVmTest1-hostdevs-add:not([disabled]):not([aria-disabled=true])","click",0,0,0,false,false,false,false)
> log: XXX WithDialogs.show {"$$typeof":"Symbol(react.element)","type":"","key":"null","ref":"null","props":"Object"}
> log: XXX WithDialogs render {"key":null,"ref":null,"props":{"idPrefix":"vm-subVmTest1-hostdevs", [...]
-> wait: ph_is_present(".pf-v5-c-modal-box .pf-v5-c-modal-box__header .pf-v5-c-modal-box__title")
> log: XXX WithDialogs render {"key":null,"ref":null,"props":{"idPrefix":"vm-subVmTest1-hostdevs",
-> ph_mouse("input#pci:not([disabled]):not([aria-disabled=true])","click",0,0,0,false,false,false,false)
> log: XXX WithDialogs.close
> log: XXX WithDialogs render null
<- {'type': 'object', 'subtype': 'error', 'className': 'Error', 'description': 'Error: input#pci:not([disabled]):not([aria-disabled=true]) not found\n    at ph_only (<anonymous>:27:15)\n    at ph_find (<anonymous>:35:12)\n    at ph_mouse (<anonymous>:111:16)\n    at <anonymous>:1:1', 'objectId': '-8674685895367023093.7.6'}
```

This is a bit unexpected -- so something calls .close() and **ALSO** the top-level `<VmDetailsPage>` seems to lose the state, even though the check in the previous comment didn't seem to corroborate that.

**Comment by martinpitt** [comment] 2023-11-09 10:20
So after discovering this, the fix is actually simple and obvious:
```diff
--- test/check-machines-hostdevs
+++ test/check-machines-hostdevs
@@ -226,6 +226,7 @@ class TestMachinesHostDevs(VirtualMachinesCase):
                 b.wait_in_text("#delete-resource-modal-vendor", self._vendor)
 
                 b.click('.pf-v5-c-modal-box__footer button:contains("Remove")')
+                b.wait_not_present("#delete-resource-modal")
                 b.wait_not_present(f"#vm-subVmTest1-hostdev-{self.vm_dev_id}-product")
 
         # Check the error if selecting no devices when the VM is running
```

But I wonder, can we make this less excruciating the next time? We *never* want to have a situation where we try to open a dialog when another one is already active.

**Comment by martinpitt** [comment] 2023-11-09 10:46
I have a dialogs.jsx improvement which will detect this situation. Unfortunately representing the component in our CDP log isn't very obvious:
```
error: Dialogs.show() called for {"$$typeof":"Symbol(react.element)","type":"","key":"null","ref":"null","props":"Object"} while a dialog is already open: {"$$typeof":"Symbol(react.element)","type":"","key":"null","ref":"null","props":"Object"}
```

It works nicely in the interactive browser though, there I can clearly see which dialog is open.

But with `JSON.stringify()` it's actually quite okay, as the point is merely to identify the dialog that is already open:
```
error: Dialogs.show() called for {"key":null,"ref":null,"props":{"idPrefix":"vm-subVmTest1-hostdevs","vm":{"state":"shut off","inactiveXML":{"connectionName":"system","name":"subVmTest1","id":"/org/libvirt/QEMU/domain/_8f37bc21_13dd_40b4_a482_5942e2cf53b3","osType":null,"osBoot":[{"order":1,"type":"disk"},{"order":2,"type":"network"}],"firmware":null,"arch":"x86_64","currentMemory":131072,"memory":131072,"memoryBacking":false,"vcpus":{"count":"1","placement":"static","max":"1"},"disks":{"vda":{"target":"vda","driver":{"name":"qemu","type":"qcow2","cache":null,"discard":null,"io":null,"errorPolicy":null},"type":"file","device":"disk","source":{"file":"/var/lib/libvirt/images/subVmTest1-2.img","dev":null,"pool":null,"volume":null,"protocol":null,"name":null,"host":{},"startupPolicy":null},"bus":"virtio","readonly":false,"shareable":false,"removable":null}},"emulatedMachine":"pc-i440fx-8.1","cpu":{"mode":"custom","model":"qemu64","topology":{}},"displays":[],"interfaces":[{"type":"network","managed":null,"name":null,"mac":"52:54:00:39:49:b2","model":"virtio","state":"up","source":{"bridge":null,"network":"default","portgroup":null,"dev":null,"mode":null,"address":null,"port":null,"local":{}},"address":{"bus":"0x00","function":"0x0","slot":"0x02","domain":"0x0000"}}],"redirectedDevices":[],"hostDevices":[],"filesystems":[],"watchdog":{},"vsock":{"cid":{}},"metadata":{"hasInstallPhase":false,"installSourceType":null,"installSource":null,"osVariant":null,"rootPassword":null,"userLogin":null,"userPassword":null}},"connectionName":"system","id":"/org/libvirt/QEMU/domain/_8f37bc21_13dd_40b4_a482_5942e2cf53b3","name":"subVmTest1","persistent":true,"autostart":false,"ui":{"initiallyExpanded":false,"initiallyOpenedConsoleTab":false},"osType":null,"osBoot":[{"order":1,"type":"disk"},{"order":2,"type":"network"}],"firmware":null,"arch":"x86_64","currentMemory":131072,"memory":131072,"memoryBacking":false,"vcpus":{"count":"1","placement":"static","max":"1"},"disks":{"vda":{"target":"vda","driver":{"name":"qemu","type":"qcow2","cache":null,"discard":null,"io":null,"errorPolicy":null},"type":"file","device":"disk","source":{"file":"/var/lib/libvirt/images/subVmTest1-2.img","dev":null,"pool":null,"volume":null,"protocol":null,"name":null,"host":{},"startupPolicy":null},"bus":"virtio","readonly":false,"shareable":false,"removable":null}},"emulatedMachine":"pc-i440fx-8.1","cpu":{"mode":"custom","model":"qemu64","topology":{}},"displays":[],"interfaces":[{"type":"network","managed":null,"name":null,"mac":"52:54:00:39:49:b2","model":"virtio","state":"up","source":{"bridge":null,"network":"default","portgroup":null,"dev":null,"mode":null,"address":null,"port":null,"local":{}},"address":{"bus":"0x00","function":"0x0","slot":"0x02","domain":"0x0000"}}],"redirectedDevices":[],"hostDevices":[],"filesystems":[],"watchdog":{},"vsock":{"cid":{}},"metadata":{"hasInstallPhase":false,"installSourceType":null,"installSource":null,"osVariant":null,"rootPassword":null,"userLogin":null,"userPassword":null},"capabilities":{"loaderElems":{"0":{}},"maxVcpu":"255","cpuModels":["qemu64","qemu32","phenom","pentium3","pentium2","pentium","n270","kvm64","kvm32","coreduo","core2duo","athlon","Westmere-IBRS","Westmere","Snowridge","Skylake-Server-noTSX-IBRS","Skylake-Server-IBRS","Skylake-Server","Skylake-Client-noTSX-IBRS","Skylake-Client-IBRS","Skylake-Client","SapphireRapids","SandyBridge-IBRS","SandyBridge","Penryn","Opteron_G5","Opteron_G4","Opteron_G3","Opteron_G2","Opteron_G1","Nehalem-IBRS","Nehalem","IvyBridge-IBRS","IvyBridge","Icelake-Server-noTSX","Icelake-Server","Haswell-noTSX-IBRS","Haswell-noTSX","Haswell-IBRS","Haswell","EPYC-Rome","EPYC-Milan","EPYC-IBPB","EPYC-Genoa","EPYC","Dhyana","Cooperlake","Conroe","Cascadelake-Server-noTSX","Cascadelake-Server","Broadwell-noTSX-IBRS","Broadwell-noTSX","Broadwell-IBRS","Broadwell","486"],"cpuHostModel":"EPYC","supportedDiskBusTypes":["ide","fdc","scsi","virtio","usb","sata"]},"snapshots":[],"usagePolling":true,"disksStats":{"vda":{"physical":"17121280","capacity":"46137344","allocation":"0"}}}},"_owner":null,"_store":{}} while a dialog is already open: {"key":null,"ref":null,"props":{"title":"Remove host device from VM?","errorMessage":"Host device could not be removed","actionDescription":"Host device will be removed from subVmTest1:","objectDescription":[{"name":"Vendor","value":"Linux Foundation"},{"name":"Product","value":"1.1 root hub"},{"name":"Device"},{"name":"Bus"}],"actionName":"Remove"},"_owner":null,"_store":{}}
```

I sent https://github.com/cockpit-project/cockpit/pull/19595 about this.

**Closed** 2023-11-09 12:33 UTC
Labels: test-flake
